# Generated by Django 4.2.30 on 2026-07-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='experience',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='photo_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='qualifications',
            field=models.TextField(blank=True, default=''),
        ),
    ]
