# Generated by Django 4.2.30 on 2026-07-13 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_facultyprofile_experience_facultyprofile_photo_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0005_add_faculty_to_classsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='academic_session',
            field=models.CharField(blank=True, default='', help_text='Academic year label, e.g. "2026-2027".', max_length=16),
        ),
        migrations.AddField(
            model_name='classsession',
            name='shift',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], default='Morning', help_text='Daily shift for this session (mirrors Section.shift).', max_length=16),
        ),
        migrations.AddField(
            model_name='classsession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='section',
            name='shift',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], default='Morning', help_text='Daily shift for this class group.', max_length=16),
        ),
        migrations.AddField(
            model_name='subject',
            name='academic_session',
            field=models.CharField(blank=True, default='', help_text='Academic year label, e.g. "2026-2027".', max_length=16),
        ),
        migrations.AddField(
            model_name='subject',
            name='faculties',
            field=models.ManyToManyField(blank=True, help_text='All faculty members who teach this subject (multi-faculty).', related_name='taught_subjects', to='faculty.facultyprofile'),
        ),
        migrations.AddField(
            model_name='subject',
            name='program',
            field=models.ForeignKey(blank=True, help_text='The program this subject belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='academics.program'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='faculty',
            field=models.ForeignKey(blank=True, help_text='Assigned faculty member for this subject (legacy single-faculty).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects_teaching', to=settings.AUTH_USER_MODEL),
        ),
    ]
